[parity]
chain = "airalab_sidechain.json"

[network]
port = 31163
bootnodes = [
]
[rpc]
disable = false
port = 8545
interface = "local"
cors = []
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub"]
hosts = ["none"]

[account]
unlock = ["0xdfd7d27b5725943e2203d2b8ddf8e594c735581a"]
password = ["password"]
keys_iterations = 600

[mining]
engine_signer = "0xdfd7d27b5725943e2203d2b8ddf8e594c735581a"
reseal_on_txs = "none"
